stages:
  - push
  - build
  - start

pushToServer:
  stage: push
  image: ubuntu
  script: 
    - which ssh || apt update && apt install -y ssh
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - chmod 400 $SSH_KEY
    - ssh -i "$SSH_KEY" $SSH_USERNAME@$SSH_ADDRESS "echo 'ini pesan dari malaikat server'"

build: #job
  stage: build
  image: ubuntu
  script: 
    - echo "Hello world"

