stages:
  - push
  - build
  - start

pushToServer:
  stage: push
  image: ubuntu
  script: 
    - which ssh || apt install openssh-server

build: #job
  stage: build
  image: ubuntu
  script: 
    - echo "Hello world"